### ISSUE TITLE
Status stay with CRITICAL - Logstash is unhealthy - CRITICAL: Config reload syntax check

### ISSUE THREAD

**Issue by Tontonitch** [widhalmt/check_logstash#19]
Hello,

We have an ELK server where the plugin stay with the message `CRITICAL - Logstash is unhealthy - CRITICAL: Config reload syntax check`, even if the config has been fixed, the service restarted and logstash is processing well.
![image](https://user-images.githubusercontent.com/600025/32235287-551dfb76-be5f-11e7-9429-b41d81388bfa.png)

Retrieveing the stats used by the plugin, I can see that indeed the last error is this config issue:
```
[root@elasticserver ~]# curl http://127.0.0.1:9600/_node/stats
{"host":"elasticserver.mydomain","version":"5.6.3","http_address":"127.0.0.1:9600","id":"xxxxxxxxxxxxxxxxxx","name":"elasticserver.mydomain","jvm":{"threads":{"count":26,"peak_count":38},"mem":{"heap_used_percent":45,"heap_committed_in_bytes":648531968,"heap_max_in_bytes":1056309248,"heap_used_in_bytes":477933248,"non_heap_used_in_bytes":131775896,"non_heap_committed_in_bytes":142356480,"pools":{"survivor":{"peak_used_in_bytes":17432576,"used_in_bytes":1062312,"peak_max_in_bytes":17432576,"max_in_bytes":17432576,"committed_in_bytes":17432576},"old":{"peak_used_in_bytes":368844480,"used_in_bytes":364530328,"peak_max_in_bytes":899284992,"max_in_bytes":899284992,"committed_in_bytes":491507712},"young":{"peak_used_in_bytes":139591680,"used_in_bytes":112340608,"peak_max_in_bytes":139591680,"max_in_bytes":139591680,"committed_in_bytes":139591680}}},"gc":{"collectors":{"old":{"collection_time_in_millis":11628,"collection_count":95},"young":{"collection_time_in_millis":143338,"collection_count":6800}}},"uptime_in_millis":113217935},"process":{"open_file_descriptors":115,"peak_open_file_descriptors":139,"max_file_descriptors":16384,"mem":{"total_virtual_in_bytes":4111454208},"cpu":{"total_in_millis":7786740,"percent":3,"load_average":{"1m":0.26,"5m":0.27,"15m":0.21}}},"pipeline":{"events":{"duration_in_millis":500853,"in":396034,"filtered":396374,"out":396374,"queue_push_duration_in_millis":14548},"plugins":{"inputs":[{"id":"6907e4d596b7e6b8d5cf08b9e71a74a053238810-2","events":{"out":396034,"queue_push_duration_in_millis":14548},"name":"http"},{"id":"6907e4d596b7e6b8d5cf08b9e71a74a053238810-1","events":{"out":0,"queue_push_duration_in_millis":0},"name":"beats"}],"filters":[{"id":"6907e4d596b7e6b8d5cf08b9e71a74a053238810-6","events":{"duration_in_millis":18239,"in":396257,"out":396257},"matches":396257,"name":"date"},{"id":"6907e4d596b7e6b8d5cf08b9e71a74a053238810-4","events":{"duration_in_millis":20,"in":340,"out":340},"name":"mutate"},{"id":"6907e4d596b7e6b8d5cf08b9e71a74a053238810-5","events":{"duration_in_millis":10626,"in":396374,"out":396257},"name":"mutate"},{"id":"6907e4d596b7e6b8d5cf08b9e71a74a053238810-3","events":{"duration_in_millis":26,"in":117,"out":340},"name":"split"}],"outputs":[{"id":"6907e4d596b7e6b8d5cf08b9e71a74a053238810-7","events":{"duration_in_millis":193669,"in":396257,"out":396257},"name":"elasticsearch"}]},"reloads":{"last_error":{"message":"Expected one of #, { at line 37, column 26 (byte 1079) after filter {\n    if [events] {\n\tsplit { field => \"[events]\" }\n    }\n    if [events][Level] {\n        mutate {\n            rename => {\n                \"[events][Level]\" => \"Level\"\n                \"[events][Exception]\" => \"Exception\"\n                \"[events][MessageTemplate]\" => \"MessageTemplate\"\n                \"[events][RenderedMessage]\" => \"RenderedMessage\"\n                \"[events][Timestamp]\" => \"Timestamp\"\n                \"[events][Properties][Application]\" => \"Properties.Application\"\n                \"[events][Properties][Environment]\" => \"Properties.Environment\"\n                \"[events][Properties][SourceContext]\" => \"Properties.SourceContext\"\n                \"[events][Renderings][Text]\" => \"Renderings.Text\"\n            }\n            remove_field => [ \"[events][Properties][0]\" ]\n        }\n     }\n     if [headers][http_host] {\n            remove_field ","backtrace":["/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:60:in `initialize'","/usr/share/logstash/logstash-core/lib/logstash/agent.rb:319:in `reload_pipeline!'","/usr/share/logstash/logstash-core/lib/logstash/agent.rb:111:in `reload_state!'","org/jruby/RubyHash.java:1342:in `each'","/usr/share/logstash/logstash-core/lib/logstash/agent.rb:108:in `reload_state!'","org/jruby/ext/thread/Mutex.java:149:in `synchronize'","/usr/share/logstash/logstash-core/lib/logstash/agent.rb:107:in `reload_state!'","/usr/share/logstash/logstash-core/lib/logstash/agent.rb:75:in `execute'","org/jruby/RubyProc.java:281:in `call'","/usr/share/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.23/lib/stud/interval.rb:20:in `interval'","/usr/share/logstash/logstash-core/lib/logstash/agent.rb:75:in `execute'","/usr/share/logstash/logstash-core/lib/logstash/runner.rb:320:in `execute'","org/jruby/RubyProc.java:281:in `call'","/usr/share/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.23/lib/stud/task.rb:24:in `initialize'"]},"successes":7,"last_success_timestamp":"2017-10-31T14:13:58.775Z","last_failure_timestamp":"2017-10-31T14:12:51.892Z","failures":7},"queue":{"events":0,"type":"persisted","capacity":{"queue_size_in_bytes":247126048,"page_capacity_in_bytes":262144000,"max_queue_size_in_bytes":1073741824,"max_unread_events":0},"data":{"path":"/var/lib/logstash/queue/main","free_space_in_bytes":5956259840,"storage_type":"xfs"}},"id":"main"},"reloads":{"successes":7,"failures":7},"os":{"cgroup":{"cpuacct":{"usage_nanos":381904708396733,"control_group":"/"},"cpu":{"cfs_quota_micros":-1,"control_group":"/","stat":{"number_of_times_throttled":0,"time_throttled_nanos":0,"number_of_elapsed_periods":0},"cfs_period_micros":100000}}}}[root@elasticserver ~]#
[root@elasticserver ~]#
```
You can also see that last success timestamp is after last_failure_timestamp.
"last_success_timestamp":"2017-10-31T14:13:58.775Z","last_failure_timestamp":"2017-10-31T14:12:51.892Z"

So, maybe the health of the logstash service should be calculated differently, maybe first by comparing the last_success_timestamp and last_failure_timestamp timestamp.

BR,
Yannick

**Comment by widhalmt** [comment]
Fixed with your PR
